import {
    addExpense,
    addFoodOrder,
    addGuest,
    addMenuItem,
    addRoom,
    buildFinalInvoiceHtmlWithDiscount,
    checkoutGuest,
    checkoutGuestWithDiscount,
    cleanupSoftDeletedRooms,
    deleteFoodOrder,
    deleteMenuItem,
    deleteRoom,
    exportHistoryCsvWithDialog,
    getActiveGuests,
    getAllGuests,
    getAvailableRoomsForGuest,
    getDashboardStats,
    getExpenses,
    getExpensesByDateRange,
    getFoodOrders,
    getFoodOrdersByGuest,
    getGuest,
    getMenuItems,
    getOrderDetails,
    getRooms,
    getTaxEnabled,
    getTaxRate,
    markOrderPaid,
    printOrderReceipt,
    setTaxEnabled,
    setTaxRate,
    toggleFoodOrderPayment,
    updateGuest,
    updateMenuItem,
    updateRoom,
    type ActiveGuestRow,
    type DashboardStats,
    type ExpenseRecord,
    type ExportFilters,
    type FoodOrderDetails,
    type FoodOrderSummary,
    type Guest,
    type MenuItem,
    type NewExpense,
    type NewFoodOrder,
    type NewGuest,
    type NewMenuItem,
    type NewRoom,
    type OrderItem,
    type Room,
} from '../client';

export type {
    ActiveGuestRow, DashboardStats, ExpenseRecord,
    ExportFilters, FoodOrderDetails, FoodOrderSummary, Guest, MenuItem, NewExpense, NewFoodOrder, NewGuest, NewMenuItem, NewRoom, OrderItem, Room
};

export const hotelRestaurantService = {
  addRoom,
  getRooms,
  getAvailableRoomsForGuest,
  updateRoom,
  deleteRoom,
  addGuest,
  getActiveGuests,
  getAllGuests,
  getGuest,
  updateGuest,
  checkoutGuest,
  addMenuItem,
  getMenuItems,
  updateMenuItem,
  deleteMenuItem,
  cleanupSoftDeletedRooms,
  addFoodOrder,
  getFoodOrders,
  getFoodOrdersByGuest,
  getOrderDetails,
  markOrderPaid,
  toggleFoodOrderPayment,
  deleteFoodOrder,
  printOrderReceipt,
  exportHistoryCsvWithDialog,
  buildFinalInvoiceHtmlWithDiscount,
  checkoutGuestWithDiscount,
  addExpense,
  getExpenses,
  getExpensesByDateRange,
  getDashboardStats,
  setTaxRate,
  getTaxRate,
  setTaxEnabled,
  getTaxEnabled,
};
