import {
    addCustomer,
    addExpense,
    addMenuItem,
    addResource,
    addSale,
    addSalePayment,
    addSaleReturn,
    checkoutCustomer,
    deleteMenuItem,
    deleteSale,
    deleteUnit,
    getActiveCustomers,
    getAvailableResourcesForCustomer,
    getCustomer,
    getCustomers,
    getExpenses,
    getExpensesByDateRange,
    getMenuItems,
    getResources,
    getSaleDetails,
    getSalePaymentSummary,
    getSaleReturnableItems,
    getSaleReturnDetails,
    getSaleReturns,
    getSales,
    getSalesByCustomer,
    markOrderPaid,
    toggleSalePayment,
    updateCustomer,
    updateMenuItem,
    updateUnit,
    type ActiveCustomerRow,
    type Customer,
    type ExpenseRecord,
    type MenuItem,
    type NewCustomer,
    type NewExpense,
    type NewMenuItem,
    type NewResource,
    type NewSale,
    type Resource,
    type SaleDetails,
    type SalePaymentSummary,
    type SaleReturnDetails,
    type SaleReturnSummary,
    type SaleSummary,
} from '../client';

export type {
    ActiveCustomerRow, Customer, ExpenseRecord, MenuItem, NewCustomer, NewExpense, NewMenuItem, NewResource, NewSale, Resource, SaleDetails, SalePaymentSummary, SaleReturnDetails, SaleReturnSummary, SaleSummary
};

export const retailService = {
  addResource,
  getResources,
  getAvailableResourcesForCustomer,
  updateResource: updateUnit,
  deleteResource: deleteUnit,
  addCustomer,
  getActiveCustomers,
  getAllCustomers: getCustomers,
  getCustomer,
  updateCustomer,
  checkoutCustomer,
  addMenuItem,
  getMenuItems,
  updateMenuItem,
  deleteMenuItem,
  addSale,
  getSales,
  getSalesByCustomer,
  getSaleDetails,
  markSalePaid: markOrderPaid,
  toggleSalePayment,
  deleteSale,
  addSalePayment,
  getSalePaymentSummary,
  getSaleReturnableItems,
  addSaleReturn,
  getSaleReturns,
  getSaleReturnDetails,
  addExpense,
  getExpenses,
  getExpensesByDateRange,
};
